server:
  port: 81

spring:
  profiles:
    active: dev
mybatis-plus:
  #  type-handlers-package: com.wrp.blog.typeHandler
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

url:
  filter:
    white-list:
      - method: POST
        url: /api/user/register
      - method: POST
        url: /api/user/login